server:
  port: 8080

database:
  user: postgres
  password: postgres

  source: jdbc:postgresql://localhost:5432/atc
  driver: org.postgresql.Driver

security:
  password:
    length: 8
  defaults:
    role: inactive