server:
  port: 8080

database:
  user: postgres
  password: postgres

  source: jdbc:postgresql://localhost:5432/atc
  driver: org.postgresql.Driver

security:
  password:
    length: 8
  defaults:
    role: admin
  jwt:
    secret: zAP5MBA4B4Ijz0MZaS48
    issuer: ATC
    validity: 36000000
    realm: atc-realm