export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const BEGIN_LIST_AJAX_CALL = "BEGIN_LIST_AJAX_CALL";
export const AJAX_LIST_CALL_ERROR = "AJAX_LIST_CALL_ERROR";

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOAD_DASHBOARD_LIST_SUCCESSFUL = 'LOAD_DASHBOARD_LIST_SUCCESSFUL';

